"""用洲际修正版 Elo 对 2026 世界杯赛程输出胜平负概率。

用法:
    python -m scripts.predict_worldcup
输出:
    outputs/wc2026_predictions.csv   机器可读
    PREDICTIONS.md                   人类可读(自动更新展示用)
"""
from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.data import load_results       # noqa: E402
from src.predict import fit_predictor, predict_fixtures, worldcup_fixtures  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT_CSV = ROOT / "outputs" / "wc2026_predictions.csv"
OUT_MD = ROOT / "PREDICTIONS.md"
PICK = {0: "主胜 / Home", 1: "平 / Draw", 2: "客胜 / Away"}


def main():
    results = load_results()
    elo, cr, head = fit_predictor(results)
    fix = predict_fixtures(worldcup_fixtures(results), elo, cr, head)
    fix["elo_home"] = [round(elo.ratings[t]) for t in fix.home_team]
    fix["elo_away"] = [round(elo.ratings[t]) for t in fix.away_team]
    fix["pick"] = [PICK[i] for i in fix[["p_home", "p_draw", "p_away"]].values.argmax(1)]

    cols = ["date", "home_team", "away_team", "neutral", "elo_home", "elo_away",
            "p_home", "p_draw", "p_away", "pick", "city"]
    out = fix[cols].reset_index(drop=True)
    OUT_CSV.parent.mkdir(exist_ok=True)
    out.to_csv(OUT_CSV, index=False)

    # —— 参赛队实力榜 ——
    teams = set(fix.home_team) | set(fix.away_team)
    rank = sorted(((round(elo.ratings[t]), t) for t in teams), reverse=True)

    last_played = results[results.played].date.max().date()
    md = [
        "# 🔮 FIFA World Cup 2026 — Match Predictions",
        "",
        f"> Auto-generated by [worldcup-predictor]"
        f"(https://github.com/hjjbh1314/worldcup-predictor) · "
        f"data up to **{last_played}** · generated **{date.today()}**",
        "",
        "Model: confederation-adjusted Elo. Probabilities are Home / Draw / Away. "
        "Not betting advice.",
        "",
        "## Strength ranking (Elo) — top 16",
        "",
        "| # | Team | Elo |",
        "|---|------|-----|",
    ]
    for i, (rt, t) in enumerate(rank[:16], 1):
        md.append(f"| {i} | {t} | {rt} |")
    md += ["", "## Group-stage fixtures", "",
           "| Date | Home | Away | Home % | Draw % | Away % | Pick |",
           "|------|------|------|:------:|:------:|:------:|------|"]
    for r in out.itertuples(index=False):
        md.append(f"| {r.date.date()} | {r.home_team} | {r.away_team} | "
                  f"{r.p_home*100:.0f}% | {r.p_draw*100:.0f}% | {r.p_away*100:.0f}% | "
                  f"{r.pick.split(' / ')[0]} |")
    OUT_MD.write_text("\n".join(md) + "\n", encoding="utf-8")

    print("=== 2026 世界杯参赛队 Elo 实力榜 Top 12 ===")
    for i, (rt, t) in enumerate(rank[:12], 1):
        print(f"  {i:2d}. {t:<22} {rt}")
    print(f"\n已写出:{OUT_CSV.name} 和 {OUT_MD.name}（{len(out)} 场）")


if __name__ == "__main__":
    main()
